DROP TABLE IF EXISTS CARRO CASCADE;
DROP SEQUENCE IF EXISTS SEQ_CARRO;

DROP TABLE IF EXISTS MOTORISTA CASCADE;
DROP SEQUENCE IF EXISTS SEQ_MOTORISTA;

CREATE SEQUENCE SEQ_CARRO;
CREATE SEQUENCE SEQ_MOTORISTA;

CREATE TABLE MOTORISTA
(ID             NUMERIC(5,0)
   CONSTRAINT MOTORISTA_ID_PK
   PRIMARY KEY,
 NOME           VARCHAR(30) 
   CONSTRAINT MOTORISTA_NOME_NN
   NOT NULL
   CONSTRAINT MOTORISTA_NOME_UN
   UNIQUE,
 DESCRICAO      VARCHAR(40),
 NUM_CARTEIRA  VARCHAR(40)
   CONSTRAINT MOTORISTA_NUM_CARTEIRA_NN
   NOT NULL,
 DATA_CADASTRO  DATE
   CONSTRAINT MOTORISTA_DATA_CADASTRO_NN
   NOT NULL);

CREATE TABLE CARRO
(ID             NUMERIC(5,0)
   CONSTRAINT CARRO_ID_PK
   PRIMARY KEY,
 VALOR          NUMERIC(8,2)
   CONSTRAINT CARRO_VALOR_NN
   NOT NULL,
 DATA_FABRICACAO   DATE
   CONSTRAINT CARRO_DATA_FABRICACAO_NN
   NOT NULL,
 MODELO 		VARCHAR(30)
   CONSTRAINT CARRO_MODELO_NN
   NOT NULL,
 PLACA			VARCHAR(30)
   CONSTRAINT CARRO_PLACA_NN
   NOT NULL,
 MOTORISTA_ID     NUMERIC(5)
   CONSTRAINT CARRO_MOTORISTA_FK
   REFERENCES MOTORISTA(ID)
   CONSTRAINT CARRO_MOTORISTA_ID_NN
   NOT NULL);

INSERT INTO MOTORISTA(ID, NOME, DESCRICAO, NUM_CARTEIRA, DATA_CADASTRO)
VALUES(NEXTVAL('SEQ_MOTORISTA'), 'PAULO', 'CATEGORIA B', '2432', current_date);

INSERT INTO CARRO(ID, VALOR, DATA_FABRICACAO, MODELO, PLACA, MOTORISTA_ID)
VALUES(NEXTVAL('SEQ_CARRO'), 22100, current_date, 'HONDA', 'ABC1234', currval('SEQ_MOTORISTA'));

INSERT INTO CARRO(ID, VALOR, DATA_FABRICACAO, MODELO, PLACA, MOTORISTA_ID)
VALUES(NEXTVAL('SEQ_CARRO'), 22200, current_date, 'TOYOTA', 'ABC5678', currval('SEQ_MOTORISTA'));

INSERT INTO MOTORISTA(ID, NOME, DESCRICAO, NUM_CARTEIRA, DATA_CADASTRO)
VALUES(NEXTVAL('SEQ_MOTORISTA'), 'RODRIGO', 'CATEGORIA D', '2500', current_date);

INSERT INTO CARRO(ID, VALOR, DATA_FABRICACAO, MODELO, PLACA, MOTORISTA_ID)
VALUES(NEXTVAL('SEQ_CARRO'), 22600, current_date, 'VOLKSWAGEN', 'DEF1234', currval('SEQ_MOTORISTA'));

INSERT INTO CARRO(ID, VALOR, DATA_FABRICACAO, MODELO, PLACA, MOTORISTA_ID)
VALUES(NEXTVAL('SEQ_CARRO'), 22700, current_date, 'NISSAN', 'GHI2345', currval('SEQ_MOTORISTA'));

COMMIT;
